CREATE TABLE "ConstellationCatalog" (
  "abbreviation" TEXT NOT NULL,
  "iauName" TEXT NOT NULL,
  "sourceName" TEXT NOT NULL,
  CONSTRAINT "ConstellationCatalog_pkey" PRIMARY KEY ("abbreviation")
);

CREATE UNIQUE INDEX "ConstellationCatalog_iauName_key" ON "ConstellationCatalog"("iauName");
CREATE UNIQUE INDEX "ConstellationCatalog_sourceName_key" ON "ConstellationCatalog"("sourceName");

INSERT INTO "ConstellationCatalog" ("abbreviation", "iauName", "sourceName") VALUES
  ('Ant', 'Antlia', 'Air Pump'),
  ('Ara', 'Ara', 'Altar'),
  ('Sgr', 'Sagittarius', 'Archer'),
  ('Sge', 'Sagitta', 'Arrow'),
  ('Com', 'Coma Berenices', 'Berenice''s Hair'),
  ('Aps', 'Apus', 'Bird of Paradise'),
  ('Tau', 'Taurus', 'Bull'),
  ('Nor', 'Norma', 'Carpenter''s Square'),
  ('Cen', 'Centaurus', 'Centaur'),
  ('And', 'Andromeda', 'Chained Maiden'),
  ('Cha', 'Chamaeleon', 'Chameleon'),
  ('Aur', 'Auriga', 'Charioteer'),
  ('Hor', 'Horologium', 'Clock'),
  ('Cnc', 'Cancer', 'Crab'),
  ('Gru', 'Grus', 'Crane'),
  ('Crv', 'Corvus', 'Crow'),
  ('Crt', 'Crater', 'Cup'),
  ('Del', 'Delphinus', 'Dolphin'),
  ('Col', 'Columba', 'Dove'),
  ('Cir', 'Circinus', 'Drafting Compass'),
  ('Dra', 'Draco', 'Dragon'),
  ('Aql', 'Aquila', 'Eagle'),
  ('Cae', 'Caelum', 'Engraving Tool'),
  ('Hya', 'Hydra', 'Female Water Snake'),
  ('Psc', 'Pisces', 'Fishes'),
  ('Mus', 'Musca', 'Fly'),
  ('Vol', 'Volans', 'Flying Fish'),
  ('Vul', 'Vulpecula', 'Fox'),
  ('For', 'Fornax', 'Furnace'),
  ('Cam', 'Camelopardalis', 'Giraffe'),
  ('UMa', 'Ursa Major', 'Great Bear'),
  ('CMa', 'Canis Major', 'Great Dog'),
  ('Lep', 'Lepus', 'Hare'),
  ('Her', 'Hercules', 'Hercules'),
  ('Boo', 'Boötes', 'Herdsman'),
  ('Per', 'Perseus', 'Hero'),
  ('Ori', 'Orion', 'Hunter'),
  ('CVn', 'Canes Venatici', 'Hunting Dogs'),
  ('Ind', 'Indus', 'Indian'),
  ('Car', 'Carina', 'Keel'),
  ('Cep', 'Cepheus', 'King'),
  ('CMi', 'Canis Minor', 'Lesser Dog'),
  ('LMi', 'Leo Minor', 'Lesser Lion'),
  ('Leo', 'Leo', 'Lion'),
  ('UMi', 'Ursa Minor', 'Little Bear'),
  ('Equ', 'Equuleus', 'Little Horse'),
  ('Lac', 'Lacerta', 'Lizard'),
  ('Lyn', 'Lynx', 'Lynx'),
  ('Lyr', 'Lyra', 'Lyre'),
  ('Pyx', 'Pyxis', 'Magnetic Compass'),
  ('Vir', 'Virgo', 'Maiden'),
  ('Hyi', 'Hydrus', 'Male Water Snake'),
  ('Mic', 'Microscopium', 'Microscope'),
  ('CrB', 'Corona Borealis', 'Northern Crown'),
  ('Oct', 'Octans', 'Octant'),
  ('Pic', 'Pictor', 'Painter''s Easel'),
  ('Pav', 'Pavo', 'Peacock'),
  ('Phe', 'Phoenix', 'Phoenix'),
  ('Ari', 'Aries', 'Ram'),
  ('Ret', 'Reticulum', 'Reticle'),
  ('Eri', 'Eridanus', 'River'),
  ('Vel', 'Vela', 'Sails'),
  ('Lib', 'Libra', 'Scales'),
  ('Sco', 'Scorpius', 'Scorpion'),
  ('Scl', 'Sculptor', 'Sculptor'),
  ('Cap', 'Capricornus', 'Sea Goat'),
  ('Cet', 'Cetus', 'Sea Monster'),
  ('Cas', 'Cassiopeia', 'Seated Queen'),
  ('Ser', 'Serpens', 'Serpent'),
  ('Oph', 'Ophiuchus', 'Serpent Bearer'),
  ('Sex', 'Sextans', 'Sextant'),
  ('Sct', 'Scutum', 'Shield'),
  ('Cru', 'Crux', 'Southern Cross'),
  ('CrA', 'Corona Australis', 'Southern Crown'),
  ('PsA', 'Piscis Austrinus', 'Southern Fish'),
  ('TrA', 'Triangulum Australe', 'Southern Triangle'),
  ('Pup', 'Puppis', 'Stern'),
  ('Cyg', 'Cygnus', 'Swan'),
  ('Dor', 'Dorado', 'Swordfish'),
  ('Men', 'Mensa', 'Table'),
  ('Tel', 'Telescopium', 'Telescope'),
  ('Tuc', 'Tucana', 'Toucan'),
  ('Tri', 'Triangulum', 'Triangle'),
  ('Gem', 'Gemini', 'Twins'),
  ('Mon', 'Monoceros', 'Unicorn'),
  ('Aqr', 'Aquarius', 'Water Bearer'),
  ('Peg', 'Pegasus', 'Winged Horse'),
  ('Lup', 'Lupus', 'Wolf');
