-- CreateTable
CREATE TABLE "hyg_stars" (
    "id" INTEGER NOT NULL,
    "hip" INTEGER,
    "hd" INTEGER,
    "hr" INTEGER,
    "gl" TEXT,
    "bf" TEXT,
    "proper" TEXT,
    "ra" DOUBLE PRECISION NOT NULL,
    "dec" DOUBLE PRECISION NOT NULL,
    "dist" DOUBLE PRECISION,
    "pmra" DOUBLE PRECISION,
    "pmdec" DOUBLE PRECISION,
    "rv" DOUBLE PRECISION,
    "mag" DOUBLE PRECISION,
    "absmag" DOUBLE PRECISION,
    "spect" TEXT,
    "ci" DOUBLE PRECISION,
    "x" DOUBLE PRECISION,
    "y" DOUBLE PRECISION,
    "z" DOUBLE PRECISION,
    "vx" DOUBLE PRECISION,
    "vy" DOUBLE PRECISION,
    "vz" DOUBLE PRECISION,
    "rarad" DOUBLE PRECISION,
    "decrad" DOUBLE PRECISION,
    "pmrarad" DOUBLE PRECISION,
    "pmdecrad" DOUBLE PRECISION,
    "bayer" TEXT,
    "flam" INTEGER,
    "con" TEXT,
    "comp" INTEGER,
    "comp_primary" INTEGER,
    "base" TEXT,
    "lum" DOUBLE PRECISION,
    "var" TEXT,
    "var_min" DOUBLE PRECISION,
    "var_max" DOUBLE PRECISION,

    CONSTRAINT "hyg_stars_pkey" PRIMARY KEY ("id")
);
