import { expect, test } from '@playwright/test';

test('mobile walkthrough scrubs one visible card in both directions without panels', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/about');
  await expect(page.locator('[data-walkthrough="mobile"]')).toBeVisible();
  const navLogo = await page.getByRole('link', { name: 'STARRY SKY' }).boundingBox();
  const introTitle = await page.getByRole('heading', { name: 'About Starry Sky' }).boundingBox();
  expect(introTitle.x).toBeCloseTo(navLogo.x, 0);
  const canvas = page.locator('canvas');
  await expect(canvas).toHaveCount(1);
  await expect.poll(() => canvas.evaluate((element) => getComputedStyle(element).touchAction)).not.toBe('none');
  await expect(page.locator('[class*="controllerParent"]')).toHaveCount(0);

  const cards = page.locator('[data-derivation-step] [class*="stepCard"]');
  const first = page.locator('[data-derivation-step="1"]');
  const second = page.locator('[data-derivation-step="2"]');
  const third = page.locator('[data-derivation-step="3"]');
  const fourth = page.locator('[data-derivation-step="4"]');
  const overheadCalc = page.locator('[class*="overheadSceneInfo"] [aria-label="Live calculation"]');
  const visibleSteps = () => cards.evaluateAll((elements) => elements
    .filter((card) => getComputedStyle(card.parentElement).opacity === '1')
    .map((card) => card.parentElement.dataset.derivationStep));
  const firstCard = first.locator('[class*="stepCard"]');
  await page.evaluate(() => document.fonts.ready);
  const firstTop = await first.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  const stage = page.locator('[class*="modelStage"]');
  const stageHeight = await stage.evaluate((stage) => stage.offsetHeight);
  const activationLine = 0;
  expect(await stage.boundingBox()).toMatchObject({ x: 0, y: 0, width: 390 });
  expect(stageHeight).toBeGreaterThan(400);
  expect(await visibleSteps()).toEqual([]);
  const intro = page.locator('[data-derivation-step="0"]');
  await page.evaluate((top) => scrollTo(0, top), firstTop - 200);
  await expect.poll(visibleSteps).toEqual([]);
  expect((await intro.boundingBox()).y + (await intro.boundingBox()).height).toBeGreaterThan(0);
  await page.evaluate((top) => scrollTo(0, top), firstTop + 100);
  await expect.poll(visibleSteps).toEqual(['1']);
  expect((await intro.boundingBox()).y + (await intro.boundingBox()).height).toBeLessThanOrEqual(0);
  expect(await stage.boundingBox()).toMatchObject({ x: 0, width: 390 });
  await expect.poll(async () => {
    const label = await page.getByText('Dec', { exact: true }).boundingBox();
    return label.x >= 0 && label.x + label.width < 180;
  }).toBe(true);
  await expect(intro).toBeVisible();
  const scene = page.locator('[class*="mobileSceneInfo"]');
  await expect(scene).not.toContainText('Find y with declination');
  await expect(firstCard.getByRole('heading', { name: 'Find y with declination' })).toBeVisible();
  const firstCalculation = await scene.getByLabel('Live calculation').boundingBox();
  expect(firstCalculation.width).toBeGreaterThan(130);
  expect(firstCalculation.x).toBeGreaterThan(240);
  expect(firstCalculation.x + firstCalculation.width).toBeCloseTo(390 - 8, 0);
  expect(firstCalculation.y).toBeCloseTo(844 * 0.18, 0);
  await expect(scene.getByLabel('Live calculation')).toContainText('y = sin(Dec)');
  await expect(firstCard.locator('[class*="stepEquation"]')).toBeHidden();
  const cardBox = await firstCard.boundingBox();
  expect(cardBox.x).toBeGreaterThanOrEqual(16);
  expect(cardBox.y + cardBox.height).toBeCloseTo(844 - 16, 0);
  await expect.poll(async () => {
    const bottomAxis = await page.getByText('-Y', { exact: true }).boundingBox();
    const readout = await scene.getByLabel('Live calculation').boundingBox();
    const card = await firstCard.boundingBox();
    return bottomAxis.y + bottomAxis.height < card.y && readout.y + readout.height < card.y;
  }).toBe(true);
  expect(await firstCard.evaluate((card) => getComputedStyle(card).borderRadius)).not.toBe('0px');
  expect(await firstCard.evaluate((card) => getComputedStyle(card, '::after').display)).toBe('none');
  const firstValue = await scene.getByLabel('Live calculation').innerText();
  const labelAtStart = await page.getByText('Dec', { exact: true }).boundingBox();
  await page.evaluate((top) => scrollTo(0, top), firstTop - activationLine + 500);
  await expect.poll(async () => {
    const label = await page.getByText('Dec', { exact: true }).boundingBox();
    return Math.abs(label.y - labelAtStart.y);
  }).toBeGreaterThan(10);
  await expect.poll(() => scene.getByLabel('Live calculation').innerText()).not.toBe(firstValue);
  const secondTop = await second.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  await page.evaluate((top) => scrollTo(0, top), secondTop - activationLine + 0.85 * 844);
  await expect.poll(visibleSteps).toEqual(['2']);
  await expect(second.locator('h2', { hasText: 'Find the horizontal radius, h' })).toBeVisible();
  await expect(scene.getByLabel('Live calculation')).toContainText('h = cos(Dec)');
  await expect.poll(async () => (await page.getByText('Dec', { exact: true }).boundingBox()).x).toBeLessThan(180);
  await expect.poll(async () => {
    const bottomAxis = await page.getByText('-Y', { exact: true }).boundingBox();
    const card = await second.locator('[class*="stepCard"]').boundingBox();
    return bottomAxis.y + bottomAxis.height < card.y;
  }).toBe(true);
  const thirdTop = await third.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  await page.evaluate((top) => scrollTo(0, top), thirdTop - activationLine + 100);
  await expect.poll(visibleSteps).toEqual(['3']);
  await page.waitForTimeout(400);
  const midPositiveZ = await page.getByText('+Z', { exact: true }).boundingBox();
  const midNegativeZ = await page.getByText('-Z', { exact: true }).boundingBox();
  expect(midPositiveZ.y).toBeGreaterThan(midNegativeZ.y);
  await expect.poll(visibleSteps).toEqual(['3']);
  await expect(scene).toHaveCount(0);
  await expect.poll(async () => {
    const positive = await page.getByText('+Z', { exact: true }).boundingBox();
    const negative = await page.getByText('-Z', { exact: true }).boundingBox();
    return positive.y > negative.y;
  }).toBe(true);
  const overheadAxisSpan = async () => {
    const positive = await page.getByText('+Z', { exact: true }).boundingBox();
    const negative = await page.getByText('-Z', { exact: true }).boundingBox();
    return Math.abs((positive.y + positive.height / 2) - (negative.y + negative.height / 2));
  };
  await expect.poll(overheadAxisSpan).toBeGreaterThan(260);
  await expect.poll(async () => {
    const north = await page.getByText('+Y', { exact: true }).boundingBox();
    const south = await page.getByText('-Y', { exact: true }).boundingBox();
    return Math.abs(north.y - south.y);
  }).toBeLessThan(20);
  await expect.poll(async () => {
    const label = await page.getByText('+Z', { exact: true }).boundingBox();
    const stageBox = await stage.boundingBox();
    return label.y + label.height <= stageBox.y + stageBox.height;
  }).toBe(true);
  await page.setViewportSize({ width: 433, height: 705 });
  await expect.poll(visibleSteps).toEqual(['3']);
  await expect.poll(async () => {
    const label = await page.getByText('+Z', { exact: true }).boundingBox();
    const stageBox = await stage.boundingBox();
    const cardBox = await third.locator('[class*="stepCard"]').boundingBox();
    return label.y + label.height <= stageBox.y + stageBox.height && label.y + label.height <= cardBox.y;
  }).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(visibleSteps).toEqual(['3']);
  await expect(overheadCalc).toContainText('x = h sin(RA)');
  const calcBox = await overheadCalc.boundingBox();
  const thirdCardBox = await third.locator('[class*="stepCard"]').boundingBox();
  expect(calcBox.x).toBeGreaterThanOrEqual(16);
  expect(calcBox.y).toBeLessThan(100);
  expect(calcBox.y + calcBox.height).toBeLessThan(thirdCardBox.y);
  const fourthTop = await fourth.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  await page.evaluate((top) => scrollTo(0, top), fourthTop - activationLine + 100);
  await expect.poll(visibleSteps).toEqual(['4']);
  await expect.poll(overheadAxisSpan).toBeGreaterThan(260);
  await expect.poll(async () => {
    const label = await page.getByText('+Z', { exact: true }).boundingBox();
    const stageBox = await stage.boundingBox();
    return label.y + label.height <= stageBox.y + stageBox.height;
  }).toBe(true);
  await expect(overheadCalc).toContainText('z = h cos(RA)');
  await page.evaluate((top) => scrollTo(0, top), firstTop - activationLine + 100);
  await expect.poll(visibleSteps).toEqual(['1']);
  await page.evaluate(() => scrollTo(0, document.body.scrollHeight));
  await expect.poll(visibleSteps).toEqual([]);
  await expect(page.getByRole('heading', { name: 'Place the star' })).toHaveCount(0);
  const sceneLabels = page.locator('[class*="sceneLabel"]');
  await expect(sceneLabels).toHaveCount(3);
  await expect(page.getByText('RA', { exact: true })).toBeVisible();
  await expect(page.getByText('Dec', { exact: true })).toBeVisible();
  await expect(sceneLabels.filter({ hasText: /^Star/ })).toHaveCount(1);
  await expect(page.locator('[class*="axisLabel"]')).toHaveCount(6);
  const enterExplore = page.getByRole('button', { name: 'Explore The Model' });
  await expect(enterExplore).toHaveText('↓Explore The Model');
  await expect(page.locator('[class*="controllerParent"]')).toHaveCount(0);
  await enterExplore.click();
  await expect(enterExplore).toBeHidden();
  await expect(page.locator('[data-mode="explore"]')).toBeVisible();
  await expect(sceneLabels).toHaveCount(3);
  await expect.poll(() => page.evaluate(() => document.documentElement.style.overflow)).toBe('hidden');
  const backToStar = page.getByRole('button', { name: 'Back to Walkthrough' });
  await expect(backToStar).toHaveText('Back to Walkthrough↑');
  await expect(backToStar).toBeFocused();
  const controller = page.locator('[class*="controllerParent"]');
  await expect(controller).toBeVisible();
  await expect(controller.getByText('Combine coordinates')).toBeVisible();
  await expect(controller.getByText(/Declination: 30\.0°/)).toBeVisible();
  await expect(controller.getByText(/Right ascension: 45\.0°/)).toBeVisible();
  const sliders = controller.getByRole('slider');
  await expect(sliders).toHaveCount(2);
  await expect(controller.getByText('Show sphere wireframe')).toHaveCount(0);
  expect((await controller.boundingBox()).y).toBeGreaterThan(stageHeight / 2);
  await sliders.first().fill('1.57');
  await sliders.last().focus();
  await sliders.last().press('Home');
  await expect(controller.getByText(/Right ascension: 90\.0°/)).toBeVisible();
  await expect(controller.getByText(/Declination: -90\.0°/)).toBeVisible();
  const finalAxisSpan = async () => {
    const positive = await page.getByText('+Y', { exact: true }).boundingBox();
    const negative = await page.getByText('-Y', { exact: true }).boundingBox();
    return Math.abs((positive.y + positive.height / 2) - (negative.y + negative.height / 2));
  };
  await expect.poll(finalAxisSpan).toBeGreaterThan(330);
  await expect.poll(() => canvas.evaluate((element) => getComputedStyle(element).touchAction)).toBe('none');
  const originalAxis = await page.getByText('+X', { exact: true }).boundingBox();
  await page.mouse.move(195, 160);
  await page.mouse.down();
  await page.mouse.move(270, 200, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => Math.abs((await page.getByText('+X', { exact: true }).boundingBox()).x - originalAxis.x)).toBeGreaterThan(5);
  const lockedScroll = await page.evaluate(() => scrollY);
  await page.mouse.wheel(0, -400);
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(lockedScroll);
  await page.getByRole('button', { name: 'Back to Walkthrough' }).click();
  await expect(enterExplore).toBeVisible();
  await expect(enterExplore).toBeFocused();
  await expect(controller).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.style.overflow)).not.toBe('hidden');
  await expect.poll(() => canvas.evaluate((element) => getComputedStyle(element).touchAction)).not.toBe('none');
  await enterExplore.click();
  await page.keyboard.press('Escape');
  await expect(enterExplore).toBeVisible();
  await page.mouse.move(195, 160);
  const beforeWheel = await page.evaluate(() => scrollY);
  await page.mouse.wheel(0, -400);
  await expect.poll(() => page.evaluate(() => scrollY)).toBeLessThan(beforeWheel);
  await page.setViewportSize({ width: 320, height: 568 });
  await page.evaluate(() => scrollTo(0, document.body.scrollHeight));
  await expect.poll(visibleSteps).toEqual([]);
  await enterExplore.click();
  await expect(page.getByRole('button', { name: 'Back to Walkthrough' })).toBeVisible();
  await page.getByRole('button', { name: 'Back to Walkthrough' }).click();
  await first.evaluate((section) => scrollTo(0, section.getBoundingClientRect().top + scrollY + 10));
  await expect.poll(visibleSteps).toEqual(['1']);
  await expect.poll(async () => {
    const readout = await scene.getByLabel('Live calculation').boundingBox();
    const label = await page.getByText('Dec', { exact: true }).boundingBox();
    return readout.y + readout.height < label.y && readout.x + readout.width <= 312;
  }).toBe(true);
});
