import { expect, test } from '@playwright/test';

test('mobile walkthrough scrubs one visible card in both directions without panels', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/about');
  await expect(page.locator('[data-walkthrough="mobile"]')).toBeVisible();
  const canvas = page.locator('canvas');
  await expect(canvas).toHaveCount(1);
  await expect.poll(() => canvas.evaluate((element) => getComputedStyle(element).touchAction)).not.toBe('none');
  await expect(page.locator('[class*="controllerParent"]')).toHaveCount(0);

  const cards = page.locator('[data-derivation-step] [class*="stepCard"]');
  const first = page.locator('[data-derivation-step="1"]');
  const second = page.locator('[data-derivation-step="2"]');
  const third = page.locator('[data-derivation-step="3"]');
  const fourth = page.locator('[data-derivation-step="4"]');
  const overheadCalc = page.locator('[class*="overheadSceneInfo"] [aria-label="Live calculation"]');
  const visibleSteps = () => cards.evaluateAll((elements) => elements
    .filter((card) => getComputedStyle(card.parentElement).opacity === '1')
    .map((card) => card.parentElement.dataset.derivationStep));
  const firstCard = first.locator('[class*="stepCard"]');
  await page.evaluate(() => document.fonts.ready);
  const firstTop = await first.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  const stage = page.locator('[class*="modelStage"]');
  const stageHeight = await stage.evaluate((stage) => stage.offsetHeight);
  expect(await stage.boundingBox()).toMatchObject({ x: 0, width: 390 });
  expect(stageHeight).toBeGreaterThan(400);
  expect(await visibleSteps()).toEqual([]);
  await page.evaluate((top) => scrollTo(0, top), firstTop - stageHeight + 100);
  await expect.poll(visibleSteps).toEqual(['1']);
  expect(await stage.boundingBox()).toMatchObject({ x: 0, width: 390 });
  await expect.poll(async () => (await page.getByText('Dec', { exact: true }).boundingBox()).x).toBeLessThan(150);
  const scene = page.locator('[class*="mobileSceneInfo"]');
  await expect(scene).not.toContainText('Find y with declination');
  await expect(firstCard.getByRole('heading', { name: 'Find y with declination' })).toBeVisible();
  expect(await firstCard.locator('h2').evaluate((heading) => getComputedStyle(heading).textAlign)).not.toBe('right');
  const firstCalculation = await scene.getByLabel('Live calculation').boundingBox();
  expect(firstCalculation.width).toBeGreaterThan(130);
  expect(firstCalculation.x).toBeGreaterThan(240);
  expect(firstCalculation.x + firstCalculation.width).toBeCloseTo(390 - 8, 0);
  await expect(scene.getByLabel('Live calculation')).toContainText('y = sin(Dec)');
  await expect(firstCard.locator('[class*="stepEquation"]')).toBeHidden();
  const cardBox = await firstCard.boundingBox();
  expect(cardBox.x).toBeGreaterThanOrEqual(16);
  expect(cardBox.y + cardBox.height).toBeCloseTo(844 - 16, 0);
  expect(await firstCard.evaluate((card) => getComputedStyle(card).borderRadius)).not.toBe('0px');
  expect(await firstCard.evaluate((card) => getComputedStyle(card, '::after').display)).toBe('none');
  const firstValue = await scene.getByLabel('Live calculation').innerText();
  const labelAtStart = await page.getByText('Dec', { exact: true }).boundingBox();
  await page.evaluate((top) => scrollTo(0, top), firstTop - stageHeight + 500);
  await expect.poll(async () => {
    const label = await page.getByText('Dec', { exact: true }).boundingBox();
    return Math.abs(label.y - labelAtStart.y);
  }).toBeGreaterThan(10);
  await expect.poll(() => scene.getByLabel('Live calculation').innerText()).not.toBe(firstValue);
  const secondTop = await second.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  await page.evaluate((top) => scrollTo(0, top), secondTop - stageHeight + 0.85 * 844);
  await expect.poll(visibleSteps).toEqual(['2']);
  await expect(second.locator('h2', { hasText: 'Find the horizontal radius, h' })).toBeVisible();
  await expect(scene.getByLabel('Live calculation')).toContainText('h = cos(Dec)');
  await expect.poll(async () => (await page.getByText('Dec', { exact: true }).boundingBox()).x).toBeLessThan(150);
  await page.evaluate((top) => scrollTo(0, top), firstTop - stageHeight + 100);
  const thirdTop = await third.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  await page.evaluate((top) => scrollTo(0, top), thirdTop - stageHeight + 100);
  await expect.poll(visibleSteps).toEqual(['3']);
  await expect(scene).toHaveCount(0);
  const overheadAxisSpan = async () => {
    const positive = await page.getByText('+Z', { exact: true }).boundingBox();
    const negative = await page.getByText('-Z', { exact: true }).boundingBox();
    return Math.abs((positive.y + positive.height / 2) - (negative.y + negative.height / 2));
  };
  await expect.poll(overheadAxisSpan).toBeGreaterThan(260);
  await expect.poll(async () => {
    const label = await page.getByText('+Z', { exact: true }).boundingBox();
    const stageBox = await stage.boundingBox();
    return label.y + label.height <= stageBox.y + stageBox.height;
  }).toBe(true);
  await page.setViewportSize({ width: 433, height: 705 });
  await expect.poll(visibleSteps).toEqual(['3']);
  await expect.poll(async () => {
    const label = await page.getByText('+Z', { exact: true }).boundingBox();
    const stageBox = await stage.boundingBox();
    return label.y + label.height <= stageBox.y + stageBox.height;
  }).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(visibleSteps).toEqual(['3']);
  await expect(overheadCalc).toContainText('x = h sin(RA)');
  const calcBox = await overheadCalc.boundingBox();
  const thirdCardBox = await third.locator('[class*="stepCard"]').boundingBox();
  expect(calcBox.x).toBeGreaterThanOrEqual(16);
  expect(calcBox.y).toBeLessThan(100);
  expect(calcBox.y + calcBox.height).toBeLessThan(thirdCardBox.y);
  const loweredModel = stage.locator('[class*="loweredModel"]');
  await expect.poll(async () => Math.round((await loweredModel.boundingBox()).y)).toBe(8);
  const fourthTop = await fourth.evaluate((section) => section.getBoundingClientRect().top + scrollY);
  await page.evaluate((top) => scrollTo(0, top), fourthTop - stageHeight + 100);
  await expect.poll(visibleSteps).toEqual(['4']);
  await expect.poll(overheadAxisSpan).toBeGreaterThan(260);
  await expect.poll(async () => {
    const label = await page.getByText('+Z', { exact: true }).boundingBox();
    const stageBox = await stage.boundingBox();
    return label.y + label.height <= stageBox.y + stageBox.height;
  }).toBe(true);
  await expect(overheadCalc).toContainText('z = h cos(RA)');
  await page.evaluate((top) => scrollTo(0, top), firstTop - stageHeight + 100);
  await expect.poll(visibleSteps).toEqual(['1']);
  await page.evaluate(() => scrollTo(0, document.body.scrollHeight));
  await expect.poll(visibleSteps).toEqual(['5']);
  await expect(page.locator('[data-derivation-step="5"] [class*="stepCard"]')).toBeVisible();
  const sceneLabels = page.locator('[class*="sceneLabel"]');
  await expect(sceneLabels).toHaveCount(3);
  await expect(page.getByText('RA', { exact: true })).toBeVisible();
  await expect(page.getByText('Dec', { exact: true })).toBeVisible();
  await expect(sceneLabels.filter({ hasText: /^Star/ })).toHaveCount(1);
  await expect(page.locator('[class*="axisLabel"]')).toHaveCount(6);
  const panel = page.locator('[data-derivation-step="5"] [class*="stepCard"]');
  const enterExplore = panel.getByRole('button', { name: 'Explore the model' });
  await expect(page.locator('[class*="controllerParent"]')).toHaveCount(0);
  await enterExplore.click();
  await expect(panel).toBeHidden();
  await expect(page.locator('[data-mode="explore"]')).toBeVisible();
  await expect(sceneLabels).toHaveCount(3);
  await expect.poll(() => page.evaluate(() => document.documentElement.style.overflow)).toBe('hidden');
  await expect(page.getByRole('button', { name: 'Back to Place the star' })).toBeFocused();
  const controller = page.locator('[class*="controllerParent"]');
  await expect(controller).toBeVisible();
  await expect(controller.getByText('Combine the coordinates')).toBeVisible();
  await expect(controller.getByText(/Declination: 30\.0°/)).toBeVisible();
  await expect(controller.getByText(/Right ascension: 45\.0°/)).toBeVisible();
  const sliders = controller.getByRole('slider');
  await expect(sliders).toHaveCount(2);
  await expect(controller.getByText('Show sphere wireframe')).toHaveCount(0);
  expect((await controller.boundingBox()).y).toBeGreaterThan(stageHeight);
  await sliders.first().fill('1.57');
  await sliders.last().focus();
  await sliders.last().press('Home');
  await expect(controller.getByText(/Right ascension: 90\.0°/)).toBeVisible();
  await expect(controller.getByText(/Declination: -90\.0°/)).toBeVisible();
  const finalModel = stage.locator('[class*="loweredModel"]');
  await expect.poll(async () => Math.round((await finalModel.boundingBox()).y)).toBe(8);
  const finalAxisSpan = async () => {
    const positive = await page.getByText('+Y', { exact: true }).boundingBox();
    const negative = await page.getByText('-Y', { exact: true }).boundingBox();
    return Math.abs((positive.y + positive.height / 2) - (negative.y + negative.height / 2));
  };
  await expect.poll(finalAxisSpan).toBeGreaterThan(330);
  await expect.poll(() => canvas.evaluate((element) => getComputedStyle(element).touchAction)).toBe('none');
  const originalAxis = await page.getByText('+X', { exact: true }).boundingBox();
  await page.mouse.move(195, 160);
  await page.mouse.down();
  await page.mouse.move(270, 200, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => Math.abs((await page.getByText('+X', { exact: true }).boundingBox()).x - originalAxis.x)).toBeGreaterThan(5);
  const lockedScroll = await page.evaluate(() => scrollY);
  await page.mouse.wheel(0, -400);
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(lockedScroll);
  await page.getByRole('button', { name: 'Back to Place the star' }).click();
  await expect(panel).toBeVisible();
  await expect(enterExplore).toBeFocused();
  await expect(controller).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.style.overflow)).not.toBe('hidden');
  await expect.poll(() => canvas.evaluate((element) => getComputedStyle(element).touchAction)).not.toBe('none');
  await enterExplore.click();
  await page.keyboard.press('Escape');
  await expect(panel).toBeVisible();
  await page.mouse.move(195, 160);
  const beforeWheel = await page.evaluate(() => scrollY);
  await page.mouse.wheel(0, -400);
  await expect.poll(() => page.evaluate(() => scrollY)).toBeLessThan(beforeWheel);
  await page.setViewportSize({ width: 320, height: 568 });
  await page.evaluate(() => scrollTo(0, document.body.scrollHeight));
  await expect.poll(visibleSteps).toEqual(['5']);
  await enterExplore.click();
  await expect(page.getByRole('button', { name: 'Back to Place the star' })).toBeVisible();
  await page.getByRole('button', { name: 'Back to Place the star' }).click();
  await first.evaluate((section) => section.scrollIntoView());
  await expect.poll(visibleSteps).toEqual(['1']);
  await expect.poll(async () => {
    const readout = await scene.getByLabel('Live calculation').boundingBox();
    const label = await page.getByText('Dec', { exact: true }).boundingBox();
    return readout.y + readout.height < label.y && readout.x + readout.width <= 312;
  }).toBe(true);
});
